Changed contained button's background color to secondary
williampj/bridgeapi.js pull request #18
Opened 2020-10-30 01:31 UTC by angeljruiz

2020-10-30 01:46 UTC, angeljruiz commented
Not really feeling the changes on hover

2020-10-30 13:27 UTC, andrewc910 commented
@angeljruiz I definitely prefer your secondary button. There seems to be a bug though. If you move your mouse ever so gently over the outlined button, the text will change color but the border takes another second to kick in.

With that said, you shouldn't be hard coding the contained buttons background color. Buttons have an api to state the color `color="secondary"`. I haven't tested but this seems like it would overwrite that api due to this being a global css thing.

I am open to discussion on this one but i think when using 2 buttons, with completely different actions, they should be different colors. I think the outline, contain adds some nice contrast but i think outline, contain, 2 tones makes it that much easier to distinguish the two. 

@williampj What are your thoughts?

2020-10-30 13:30 UTC, andrewc910 requested changes

2020-10-30 13:30 UTC, andrewc910 commented on src/theme.js
> +        backgroundColor: secondary,
Wouldn't this force all buttons that use `color=primary` to be the secondary color? Why not just change the buttons api usage? This could cause quite a bit of confusion later on.

2020-11-03 06:21 UTC, angeljruiz commented on src/theme.js
> +        backgroundColor: secondary,
I was implementing the designer's button color scheme suggestions. I went globally because adding `color=primary` to every button in the app would be a bit of a hassle
Initially, I didn't particularly like the suggestions but they've grown on me

2020-11-03 06:46 UTC, angeljruiz commented
I removed the color swap & changed the font from black to white on secondary buttons

2020-11-03 13:46 UTC, merged